### ISSUE TITLE
Refactor main.py to handle different paper types

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#142]
I found it is a little difficult to follow the current `main.py` because we have different types of papers (main conference, SRW, demo).
And the `papers.csv`, `poster_schedule.yml`, `papers_recs.json`, `papers_projection.json` all not synced.

I'll work on a refactor of the `main.py` if I have time.
But for now, we need to figure out the steps to sync these files.
cc @GuyAglionby @georgepar @ardakdemir since you three have touched these files.

**Comment by hao-fang** [comment]
and cc @prabhat1081 who has been working on extracting the images from PDFs

**Comment by GuyAglionby** [comment]
The 3 types of paper are differentiated by their volume, stored as part of the ID. As they share all the same fields they could share the same `paper.csv` and just be filtered on load, though it may be easier for ingestion reasons if they're stored in their own files.

`papers.csv` and `poster_schedule.yml` can certainly be generated in the same script to ensure consistency.

I think the most useful thing to do to ensure consistency across all files would be to define an expected format of all paper info (name, authors, abstract, paper type, track, qa sessions/links, etc.) and feed this to a makefile that runs the appropriate scripts. One difficulty might be that creating the recs and projections takes a bit of time, so it would be nice if we could detect whether or not they need regeneration. (If they don't actually take too long then this is less of an issue.)

This probably relates to https://github.com/Mini-Conf/Mini-Conf/issues/36 - when considering the input format above, keeping what comes from softconf vs what doesn't separate will make contributing upstream easier.

**Comment by georgepar** [comment]
@hao-fang After this refactoring I get the following error when trying to run make freeze (I've pulled master for the repo and the sitedata)

```
➜ make freeze                    
rm -rf build/
python3 main.py sitedata_acl2020/ --build
Data Successfully Loaded
[2020-06-22 17:11:01,476] ERROR in app: Exception on /papers.json [GET]
Traceback (most recent call last):
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 207, in papers_json
    return jsonify(site_data["posters"])
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/home/george/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/home/george/anaconda3/lib/python3.7/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/george/anaconda3/lib/python3.7/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/home/george/anaconda3/lib/python3.7/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type Poster is not JSON serializable
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    freezer.freeze()
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask_frozen/__init__.py", line 199, in freeze
    return set(page.url for page in self.freeze_yield())
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask_frozen/__init__.py", line 199, in <genexpr>
    return set(page.url for page in self.freeze_yield())
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask_frozen/__init__.py", line 183, in freeze_yield
    new_filename = self._build_one(url)
  File "/home/george/anaconda3/lib/python3.7/site-packages/flask_frozen/__init__.py", line 322, in _build_one
    % (response.status, url))
ValueError: Unexpected status '500 INTERNAL SERVER ERROR' on URL /papers.json
Makefile:26: recipe for target 'freeze' failed
make: *** [freeze] Error 1
```
Did something break, or am I doing smth wrong?

**Comment by hao-fang** [comment]
@georgepar hmm.. interesting, it works on my local env & in the GitHub Action.
Can you try `pip install -r requirements.txt`? I added `jsons` to the requirements so you might miss that package for serializing dataclasses.
