### ISSUE TITLE
Incorrect Link in Demo Paper 50

### ISSUE THREAD

**Issue by americast** [acl-org/acl-2020-virtual-conference#517]
From Rocketchat https://acl2020.rocket.chat/channel/helpdesk?msg=dyTjtLnYsQ3Y2oQQY

The link for this demo paper is unfortunately wrong — https://virtual.acl2020.org/paper_demo.90.html. It links to https://syntaxgym.org but should be http://syntaxgym.org.

I shall provide a quick fix for this.

**Comment by ariepratama** [comment]
@americast this PR causes error when building locally

```
export FLASK_DEBUG=True; export FLASK_DEVELOPMENT=True; python3 main.py sitedata_acl2020/
Traceback (most recent call last):
  File "main.py", line 261, in <module>
    extra_files = load_site_data(args.path, site_data, by_uid, qa_session_length_hr)
  File "/home/arie/external/acl-2020-virtual-conference/miniconf/load_site_data.py", line 176, in load_site_data
    paper_images_path=site_data["config"]["paper_images_path"],
  File "/home/arie/external/acl-2020-virtual-conference/miniconf/load_site_data.py", line 487, in build_papers
    for item in raw_papers
  File "/home/arie/external/acl-2020-virtual-conference/miniconf/load_site_data.py", line 487, in <listcomp>
    for item in raw_papers
  File "<string>", line 14, in __init__
  File "/home/arie/external/acl-2020-virtual-conference/miniconf/site_data.py", line 69, in __post_init__
    assert self.demo_url.startswith("https://"), self.demo_url
AssertionError: http://syntaxgym.org/
Makefile:23: recipe for target 'run' failed
make: *** [run] Error 1
```

will it ok on production side? just confirming

**Comment by americast** [comment]
Hi @ariepratama,

  Thanks a lot for response. This has been taken care of in https://github.com/acl-org/acl-2020-virtual-conference/pull/519/commits/5d6d9d11eeb269621d90a0bc196e1f3cc04b43de.

Thanks again! :smile:
